services:
  db:
    image: mysql:8.0
    container_name: locadora_mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'locadora_db'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: