package com.locadora.domain;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Represents a customer (Cliente) entity in the vehicle rental system.
 * <p>
 * This class encapsulates customer information such as name, CPF, and email.
 * It uses Lombok annotations to generate getters, setters, equals, hashCode, and toString methods.
 * </p>
 * <p>
 * Representa uma entidade de cliente no sistema de aluguel de veículos.
 * Esta classe encapsula informações do cliente como nome, CPF e email.
 * Utiliza anotações Lombok para gerar getters, setters, equals, hashCode e método toString.
 * </p>
 *
 * @author Locadora de Veículos
 * @version 1.0
 * @since 2024
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Cliente {
    /**
     * Unique identifier for the customer.
     * <br>Identificador único do cliente.
     */
    private Long id;

    /**
     * Customer's full name.
     * <br>Nome completo do cliente.
     */
    private String nome;

    /**
     * Customer's CPF (Cadastro de Pessoas Físicas - Brazilian tax ID).
     * <br>CPF do cliente (Cadastro de Pessoas Físicas - Documento de Identidade Tributária Brasileira).
     */
    private String cpf;

    /**
     * Customer's email address.
     * <br>Endereço de email do cliente.
     */
    private String email;

    /**
     * Constructs a Cliente with name, CPF, and email.
     * <p>
     * Constructs a new Cliente object with the specified name, CPF, and email.
     * The ID is not set in this constructor and will be generated by the database.
     * </p>
     * <p>
     * Constrói um Cliente com nome, CPF e email.
     * Constrói um novo objeto Cliente com o nome, CPF e email especificados.
     * O ID não é definido neste construtor e será gerado pelo banco de dados.
     * </p>
     *
     * @param nome  the customer's full name / nome completo do cliente
     * @param cpf   the customer's CPF / CPF do cliente
     * @param email the customer's email address / endereço de email do cliente
     */
    public Cliente(String nome, String cpf, String email) {
        this.nome = nome;
        this.cpf = cpf;
        this.email = email;
    }
}
