package com.locadora.domain;

import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Represents a vehicle (Veiculo) entity in the vehicle rental system.
 * <p>
 * This class encapsulates vehicle information such as license plate, model, daily rate, and status.
 * It uses Lombok annotations to generate getters, setters, equals, hashCode, and toString methods.
 * </p>
 * <p>
 * Representa uma entidade de veículo no sistema de aluguel de veículos.
 * Esta classe encapsula informações do veículo como placa, modelo, taxa diária e status.
 * Utiliza anotações Lombok para gerar getters, setters, equals, hashCode e método toString.
 * </p>
 *
 * @author Locadora de Veículos
 * @version 1.0
 * @since 2024
 */
@Data
@NoArgsConstructor
public class Veiculo {
    /**
     * Unique identifier for the vehicle.
     * <br>Identificador único do veículo.
     */
    private Long id;

    /**
     * Vehicle's license plate.
     * <br>Placa do veículo.
     */
    private String placa;

    /**
     * Vehicle's model name.
     * <br>Modelo do veículo.
     */
    private String modelo;

    /**
     * Daily rental rate for the vehicle in Brazilian Reais (R$).
     * <br>Taxa de aluguel diário do veículo em Reais (R$).
     */
    private double valorDiaria;

    /**
     * Current status of the vehicle (DISPONIVEL, ALUGADO, etc.).
     * <br>Status atual do veículo (DISPONIVEL, ALUGADO, etc.).
     */
    private Status status;

    /**
     * Constructs a Veiculo with plate, model, daily rate, and status.
     * <p>
     * Constructs a new Veiculo object with the specified plate, model, daily rate, and status.
     * The ID is not set in this constructor and will be generated by the database.
     * </p>
     * <p>
     * Constrói um Veiculo com placa, modelo, taxa diária e status.
     * Constrói um novo objeto Veiculo com placa, modelo, taxa diária e status especificados.
     * O ID não é definido neste construtor e será gerado pelo banco de dados.
     * </p>
     *
     * @param placa        the vehicle's license plate / placa do veículo
     * @param modelo       the vehicle's model / modelo do veículo
     * @param valorDiaria  the daily rental rate / taxa de aluguel diário
     * @param status       the current status of the vehicle / status atual do veículo
     */
    public Veiculo(String placa, String modelo, double valorDiaria, Status status) {
        this.placa = placa;
        this.modelo = modelo;
        this.valorDiaria = valorDiaria;
        this.status = status;
    }

    /**
     * Constructs a Veiculo with all attributes including ID.
     * <p>
     * Constructs a new Veiculo object with all attributes including the ID.
     * This constructor is typically used when retrieving vehicles from the database.
     * </p>
     * <p>
     * Constrói um Veiculo com todos os atributos incluindo o ID.
     * Este construtor é tipicamente usado ao recuperar veículos do banco de dados.
     * </p>
     *
     * @param id           the vehicle's unique identifier / identificador único do veículo
     * @param placa        the vehicle's license plate / placa do veículo
     * @param modelo       the vehicle's model / modelo do veículo
     * @param valorDiaria  the daily rental rate / taxa de aluguel diário
     * @param status       the current status of the vehicle / status atual do veículo
     */
    public Veiculo(Long id, String placa, String modelo, double valorDiaria, Status status) {
        this.id = id;
        this.placa = placa;
        this.modelo = modelo;
        this.valorDiaria = valorDiaria;
        this.status = status;
    }

    /**
     * Returns a formatted string representation of the vehicle.
     * <p>
     * Format: 🚗 [PLATE] MODEL | Daily Rate: R$ VALUE | Status: STATUS
     * </p>
     * <p>
     * Retorna uma representação em string formatada do veículo.
     * Formato: 🚗 [PLACA] MODELO | Diária: R$ VALOR | Status: STATUS
     * </p>
     *
     * @return a formatted string representation of the vehicle
     *         / uma representação em string formatada do veículo
     */
    @Override
    public String toString() {
        return String.format("🚗 [%s] %-7s | Diária: R$ %6.2f | Status: %s\n",
                placa, modelo, valorDiaria, status);
    }
}
